const terms = {
  title: 'Términos de servicio',
  content:
    'Huru Inc. y sus subsidiarias (colectivamente, "Huru", "nosotros" o "nos"), brindan una plataforma para compartir autos en línea que conecta a los propietarios de vehículos con viajeros y lugareños que buscan reservar esos vehículos. Se puede acceder a Huru en línea, incluso en Huru.com y como una aplicación para dispositivos móviles. Los sitios web, el blog, las aplicaciones móviles y los servicios asociados de Huru se denominan colectivamente "los Servicios". Al acceder o utilizar los Servicios, incluso al comunicarse con nosotros u otros usuarios de Huru, usted acepta cumplir y estar legalmente obligado por las disposiciones de estos Términos de servicio (estos "Términos"), ya sea que se registre o no usuario de los Servicios. Estos Términos rigen su acceso y uso de los Servicios y constituyen un acuerdo legal vinculante entre usted y Huru. Estos Términos, junto con la Política de privacidad de Huru, los términos y certificados de seguro aplicables, los términos de asistencia en la carretera y las Políticas de usuario accesibles a través de los Servicios (las "Políticas") constituyen el "Acuerdo" entre usted y Huru (cada uno es una "Parte" y juntos , "las fiestas"). Modificación. Huru se reserva el derecho, a nuestro exclusivo criterio, de modificar los Servicios o modificar el Acuerdo, incluidos estos Términos, en cualquier momento. Si modificamos estos Términos, publicaremos la modificación en los Servicios. También actualizaremos la fecha de "Última revisión" en la parte superior de estos Términos. Si continúa accediendo o utilizando los Servicios después de que hayamos publicado una modificación o le hayamos proporcionado un aviso de una modificación, está indicando que acepta estar sujeto a los términos modificados. Si los términos modificados no son aceptables para usted, su único recurso es dejar de usar y acceder a los Servicios y cerrar su Cuenta Huru dentro de los 30 días. Si opta por cerrar su Cuenta Huru, se le aplicará la versión anterior vigente de estos Términos, a menos que utilice los Servicios durante el período intermedio de 30 días, en cuyo caso se le aplicará la nueva versión de estos Términos.',
};
const privacy = {
  title: 'Política de privacidad',
  content: `La misión de Huru es ayudar a establecer vínculos entre personas y hacer de este mundo un lugar más abierto e inclusivo. En resumen, construir un mundo en el que todos nos sintamos como en casa donde vayamos. Nuestra comunidad se basa en la confianza. Para ganárnosla es fundamental que todos los miembros tengan claro cómo utilizamos sus datos y protegemos su derecho a la privacidad.Esta Política de Privacidad describe cómo Huru, Inc. y sus empresas afiliadas (nosotros, nos, o Huru) tratan los datos personales que recopilamos a través de la Plataforma Huru. Dependiendo de dónde vivas y de lo que estés haciendo en la plataforma Huru, las páginas de privacidad complementarias que se enumeran a continuación pueden aplicarse a ti. Por favor, sigue los enlaces y revisa la información complementaria proporcionada allí con información sobre cómo procesamos la información personal para esas regiones y servicios.`,
};

export { terms, privacy };
